/**
 * Liquid Generator - Main orchestrator for HTML to Shopify Liquid conversion
 * Coordinates the Gemini client, CSS scoper, and schema builder
 */

import { GeminiClient, ConversionInput, ConversionResult } from './geminiClient';
import { scopeCss, generateSectionCssFile, ScopedCssResult } from './cssScoper';
import { 
  buildSectionSchema, 
  schemaToLiquid, 
  parseSchemaFromLiquid,
  ExtractedContent,
  SectionSchema 
} from './schemaBuilder';

export interface LiquidGeneratorConfig {
  geminiApiKey: string;
  geminiModel?: string;
  maxRetries?: number;
  rateLimitPerMinute?: number;
}

export interface SectionInput {
  sectionName: string;
  sectionType: string;
  sourceUrl: string;
  html: string;
  css: string;
  screenshot?: string; // base64 encoded
}

export interface GeneratedSection {
  name: string;
  type: string;
  liquidContent: string;
  cssContent: string;
  jsContent: string;
  schema: SectionSchema;
}

export interface GenerationResult {
  success: boolean;
  section?: GeneratedSection;
  errors: string[];
  warnings: string[];
}

/**
 * Extract content from HTML for schema generation
 */
export function extractContentFromHtml(html: string): ExtractedContent {
  const content: ExtractedContent = {
    headings: [],
    texts: [],
    images: [],
    links: [],
    colors: [],
    backgroundImages: []
  };
  
  // Extract headings (h1-h6)
  const headingMatches = html.matchAll(/<h[1-6][^>]*>([^<]+)<\/h[1-6]>/gi);
  for (const match of headingMatches) {
    content.headings.push(match[1].trim());
  }
  
  // Extract paragraph texts
  const textMatches = html.matchAll(/<p[^>]*>([^<]+)<\/p>/gi);
  for (const match of textMatches) {
    const text = match[1].trim();
    if (text.length > 10) { // Only meaningful text
      content.texts.push(text);
    }
  }
  
  // Extract image sources
  const imgMatches = html.matchAll(/<img[^>]+src=["']([^"']+)["'][^>]*>/gi);
  for (const match of imgMatches) {
    content.images.push(match[1]);
  }
  
  // Extract links
  const linkMatches = html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([^<]*)<\/a>/gi);
  for (const match of linkMatches) {
    content.links.push({
      url: match[1],
      text: match[2].trim()
    });
  }
  
  // Extract inline colors
  const colorMatches = html.matchAll(/(?:color|background-color)\s*:\s*(#[0-9a-fA-F]{3,8}|rgb[a]?\([^)]+\))/gi);
  for (const match of colorMatches) {
    if (!content.colors.includes(match[1])) {
      content.colors.push(match[1]);
    }
  }
  
  // Extract background images
  const bgImageMatches = html.matchAll(/background(?:-image)?\s*:\s*url\(['"]?([^'")\s]+)['"]?\)/gi);
  for (const match of bgImageMatches) {
    content.backgroundImages.push(match[1]);
  }
  
  return content;
}

/**
 * Generate a minimal JavaScript file for the section
 */
export function generateSectionJs(sectionName: string): string {
  return `/**
 * Section: ${sectionName}
 * Generated by ThemeForge
 */

(function() {
  'use strict';

  // Section initialization
  const sectionClass = 'section-${sectionName.toLowerCase().replace(/\s+/g, '-')}';
  
  function initSection() {
    const sections = document.querySelectorAll('.' + sectionClass);
    sections.forEach(function(section) {
      // Add any section-specific JavaScript here
      section.setAttribute('data-initialized', 'true');
    });
  }

  // Initialize on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initSection);
  } else {
    initSection();
  }

  // Re-initialize on Shopify section events
  document.addEventListener('shopify:section:load', function(event) {
    if (event.target.classList.contains(sectionClass)) {
      initSection();
    }
  });
})();
`;
}

/**
 * Post-process the generated Liquid content
 */
export function postProcessLiquid(
  liquid: string, 
  sectionName: string
): string {
  let processed = liquid;
  
  // Replace placeholder section names
  processed = processed.replace(/SECTION_NAME/g, sectionName);
  processed = processed.replace(/\[name\]/g, sectionName.toLowerCase().replace(/\s+/g, '-'));
  
  // Ensure proper asset references
  const sectionSlug = sectionName.toLowerCase().replace(/\s+/g, '-');
  processed = processed.replace(
    /{{ 'section-[^']+\.css' \| asset_url \| stylesheet_tag }}/g,
    `{{ 'section-${sectionSlug}.css' | asset_url | stylesheet_tag }}`
  );
  processed = processed.replace(
    /{{ 'section-[^']+\.js' \| asset_url }}/g,
    `{{ 'section-${sectionSlug}.js' | asset_url }}`
  );
  
  return processed;
}

/**
 * LiquidGenerator class - main orchestrator
 */
export class LiquidGenerator {
  private geminiClient: GeminiClient;
  
  constructor(config: LiquidGeneratorConfig) {
    this.geminiClient = new GeminiClient({
      apiKey: config.geminiApiKey,
      model: config.geminiModel,
      maxRetries: config.maxRetries,
      rateLimitPerMinute: config.rateLimitPerMinute
    });
  }
  
  /**
   * Generate a complete Shopify section from HTML
   */
  async generateSection(input: SectionInput): Promise<GenerationResult> {
    const errors: string[] = [];
    const warnings: string[] = [];
    
    try {
      // Step 1: Extract content from HTML
      const extractedContent = extractContentFromHtml(input.html);
      
      // Step 2: Scope CSS
      const sectionSlug = input.sectionName.toLowerCase().replace(/\s+/g, '-');
      const scopedCssResult = scopeCss(input.css, {
        sectionId: '{{ section.id }}',
        sectionClass: `section-${sectionSlug}`
      });
      warnings.push(...scopedCssResult.warnings);
      
      // Step 3: Generate Liquid via Gemini
      const conversionInput: ConversionInput = {
        sectionType: input.sectionType,
        sourceUrl: input.sourceUrl,
        sectionHTML: input.html,
        sectionCSS: scopedCssResult.scopedCss,
        screenshot: input.screenshot
      };
      
      const conversionResult = await this.geminiClient.convertToLiquid(conversionInput);
      
      if (!conversionResult.success || !conversionResult.liquidContent) {
        errors.push(conversionResult.error || 'Failed to generate Liquid content');
        return { success: false, errors, warnings };
      }
      
      // Step 4: Post-process Liquid
      const liquidContent = postProcessLiquid(
        conversionResult.liquidContent, 
        input.sectionName
      );
      
      // Step 5: Parse and validate schema
      let schema = parseSchemaFromLiquid(liquidContent);
      if (!schema) {
        // Generate schema if not present or invalid
        schema = buildSectionSchema({
          sectionName: input.sectionName,
          sectionType: input.sectionType,
          includeDefaultSettings: true,
          extractedContent
        });
        warnings.push('Schema was regenerated due to parsing issues');
      }
      
      // Step 6: Generate CSS file
      const cssContent = generateSectionCssFile(sectionSlug, input.css);
      
      // Step 7: Generate JS file
      const jsContent = generateSectionJs(input.sectionName);
      
      return {
        success: true,
        section: {
          name: input.sectionName,
          type: input.sectionType,
          liquidContent,
          cssContent,
          jsContent,
          schema
        },
        errors,
        warnings
      };
      
    } catch (error) {
      errors.push(error instanceof Error ? error.message : 'Unknown error occurred');
      return { success: false, errors, warnings };
    }
  }
  
  /**
   * Generate multiple sections in parallel
   */
  async generateSections(
    inputs: SectionInput[], 
    concurrency: number = 5
  ): Promise<Map<string, GenerationResult>> {
    const results = new Map<string, GenerationResult>();
    
    // Process in batches to respect rate limits
    for (let i = 0; i < inputs.length; i += concurrency) {
      const batch = inputs.slice(i, i + concurrency);
      const batchPromises = batch.map(input => 
        this.generateSection(input).then(result => ({ name: input.sectionName, result }))
      );
      
      const batchResults = await Promise.all(batchPromises);
      for (const { name, result } of batchResults) {
        results.set(name, result);
      }
      
      // Small delay between batches for rate limiting
      if (i + concurrency < inputs.length) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
    }
    
    return results;
  }
}

export default LiquidGenerator;
