import { NextRequest, NextResponse } from 'next/server';
import { getJobStore } from '@/lib/jobStore';

interface FileNode {
  name: string;
  type: 'folder' | 'file';
  children?: FileNode[];
  path?: string;
  count?: number;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ jobId: string }> }
) {
  const { jobId } = await params;
  const jobStore = getJobStore();
  const searchParams = request.nextUrl.searchParams;
  const wantTree = searchParams.get('tree') === 'true';
  const filePath = searchParams.get('file');

  const job = jobStore.get(jobId);

  if (!job) {
    return NextResponse.json(
      { error: 'Job not found' },
      { status: 404 }
    );
  }

  // If requesting file content
  if (filePath) {
    const content = getFileContent(filePath);
    if (content) {
      return NextResponse.json({ content });
    }
    return NextResponse.json(
      { error: 'File not found' },
      { status: 404 }
    );
  }

  // If requesting file tree
  if (wantTree) {
    const tree = generateFileTree();
    return NextResponse.json({ tree });
  }

  // Return theme result summary
  const hostname = job.url ? new URL(job.url).hostname : 'website';
  
  return NextResponse.json({
    url: job.url,
    screenshot: null, // Would be actual screenshot path in production
    stats: {
      sections: 8,
      templates: 3,
      css: 1,
      js: 1,
    },
    sections: ['header', 'hero', 'features', 'testimonials', 'pricing', 'faq', 'newsletter', 'footer'],
    fileSize: '4.2 MB',
  });
}

function generateFileTree(): FileNode {
  return {
    name: 'theme',
    type: 'folder',
    children: [
      {
        name: 'assets',
        type: 'folder',
        count: 52,
        children: [
          { name: 'base.css', type: 'file', path: 'assets/base.css' },
          { name: 'theme.js', type: 'file', path: 'assets/theme.js' },
          { name: 'image-hero-bg.webp', type: 'file', path: 'assets/image-hero-bg.webp' },
        ],
      },
      {
        name: 'sections',
        type: 'folder',
        count: 8,
        children: [
          { name: 'header.liquid', type: 'file', path: 'sections/header.liquid' },
          { name: 'hero.liquid', type: 'file', path: 'sections/hero.liquid' },
          { name: 'features.liquid', type: 'file', path: 'sections/features.liquid' },
          { name: 'testimonials.liquid', type: 'file', path: 'sections/testimonials.liquid' },
          { name: 'pricing.liquid', type: 'file', path: 'sections/pricing.liquid' },
          { name: 'faq.liquid', type: 'file', path: 'sections/faq.liquid' },
          { name: 'newsletter.liquid', type: 'file', path: 'sections/newsletter.liquid' },
          { name: 'footer.liquid', type: 'file', path: 'sections/footer.liquid' },
        ],
      },
      {
        name: 'templates',
        type: 'folder',
        count: 7,
        children: [
          { name: 'index.json', type: 'file', path: 'templates/index.json' },
          { name: 'page.json', type: 'file', path: 'templates/page.json' },
          { name: 'article.json', type: 'file', path: 'templates/article.json' },
        ],
      },
      {
        name: 'config',
        type: 'folder',
        count: 2,
        children: [
          { name: 'settings_schema.json', type: 'file', path: 'config/settings_schema.json' },
          { name: 'settings_data.json', type: 'file', path: 'config/settings_data.json' },
        ],
      },
      {
        name: 'layout',
        type: 'folder',
        count: 1,
        children: [
          { name: 'theme.liquid', type: 'file', path: 'layout/theme.liquid' },
        ],
      },
      {
        name: 'snippets',
        type: 'folder',
        count: 1,
        children: [
          { name: 'icon.liquid', type: 'file', path: 'snippets/icon.liquid' },
        ],
      },
    ],
  };
}

function getFileContent(path: string): string | null {
  // Return sample content for different file types
  const contentMap: Record<string, string> = {
    'sections/hero.liquid': `{%- comment -%}
  Hero Section - Generated by ThemeForge
{%- endcomment -%}

<section class="section-hero" id="hero">
  <div class="container">
    <div class="section-hero__inner">
      {% if section.settings.heading != blank %}
        <h2 class="section-hero__heading">
          {{ section.settings.heading }}
        </h2>
      {% endif %}
      
      {% if section.settings.description != blank %}
        <p class="section-hero__description">
          {{ section.settings.description }}
        </p>
      {% endif %}
      
      <div class="section-hero__content">
        {%- for block in section.blocks -%}
          <div class="section-hero__item" {{ block.shopify_attributes }}>
            {% if block.settings.title != blank %}
              <h3>{{ block.settings.title }}</h3>
            {% endif %}
            {% if block.settings.text != blank %}
              <p>{{ block.settings.text }}</p>
            {% endif %}
          </div>
        {%- endfor -%}
      </div>
    </div>
  </div>
</section>

{% schema %}
{
  "name": "Hero",
  "tag": "section",
  "class": "section-hero",
  "settings": [
    {
      "type": "text",
      "id": "heading",
      "label": "Heading",
      "default": "Welcome"
    },
    {
      "type": "textarea",
      "id": "description",
      "label": "Description"
    }
  ],
  "blocks": [
    {
      "type": "item",
      "name": "Item",
      "settings": [
        {
          "type": "text",
          "id": "title",
          "label": "Title"
        },
        {
          "type": "richtext",
          "id": "text",
          "label": "Text"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "Hero"
    }
  ]
}
{% endschema %}`,
    'sections/features.liquid': `{%- comment -%}
  Features Section - Generated by ThemeForge
{%- endcomment -%}

<section class="section-features" id="features">
  <div class="container">
    <div class="section-features__inner">
      {% if section.settings.heading != blank %}
        <h2 class="section-features__heading">
          {{ section.settings.heading }}
        </h2>
      {% endif %}
      
      <div class="section-features__grid">
        {%- for block in section.blocks -%}
          <div class="feature-card" {{ block.shopify_attributes }}>
            {% if block.settings.icon != blank %}
              <div class="feature-card__icon">
                {{ block.settings.icon }}
              </div>
            {% endif %}
            {% if block.settings.title != blank %}
              <h3 class="feature-card__title">
                {{ block.settings.title }}
              </h3>
            {% endif %}
            {% if block.settings.description != blank %}
              <p class="feature-card__description">
                {{ block.settings.description }}
              </p>
            {% endif %}
          </div>
        {%- endfor -%}
      </div>
    </div>
  </div>
</section>

{% schema %}
{
  "name": "Features",
  "settings": [
    {
      "type": "text",
      "id": "heading",
      "label": "Heading",
      "default": "Features"
    }
  ],
  "blocks": [
    {
      "type": "feature",
      "name": "Feature",
      "settings": [
        {
          "type": "text",
          "id": "icon",
          "label": "Icon (emoji or text)"
        },
        {
          "type": "text",
          "id": "title",
          "label": "Title"
        },
        {
          "type": "textarea",
          "id": "description",
          "label": "Description"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "Features"
    }
  ]
}
{% endschema %}`,
    'assets/base.css': `/* Base CSS - Generated by ThemeForge */

:root {
  --color-base-background: #ffffff;
  --color-base-text: #121212;
  --color-base-accent: #f97316;
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
  color: var(--color-base-text);
  background-color: var(--color-base-background);
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem;
}

section {
  padding: 4rem 0;
}`,
    'assets/theme.js': `/* Theme JavaScript - Generated by ThemeForge */

(function() {
  'use strict';
  
  document.addEventListener('DOMContentLoaded', function() {
    console.log('ThemeForge theme initialized');
  });
})();`,
  };

  return contentMap[path] || null;
}
