import * as csstree from 'css-tree';
import type { CssNode } from 'css-tree';

/**
 * Extract CSS rules that apply to a specific section
 */
export function extractSectionCSS(
  fullCSS: string,
  sectionSelector: string,
  classList: string[]
): string {
  const relevantRules: string[] = [];
  
  try {
    const ast = csstree.parse(fullCSS);
    
    csstree.walk(ast, {
      enter(node: CssNode) {
        if (node.type === 'Rule') {
          const selectorText = csstree.generate(node.prelude);
          
          // Check if this rule applies to the section
          if (isRelevantSelector(selectorText, sectionSelector, classList)) {
            relevantRules.push(csstree.generate(node));
          }
        }
        
        // Handle @media rules
        if (node.type === 'Atrule' && node.name === 'media') {
          const mediaRules: string[] = [];
          
          csstree.walk(node, {
            enter(child: CssNode) {
              if (child.type === 'Rule') {
                const selectorText = csstree.generate(child.prelude);
                if (isRelevantSelector(selectorText, sectionSelector, classList)) {
                  mediaRules.push(csstree.generate(child));
                }
              }
            },
          });
          
          if (mediaRules.length > 0) {
            const mediaCondition = node.prelude ? csstree.generate(node.prelude) : '';
            relevantRules.push(`@media ${mediaCondition} { ${mediaRules.join('\n')} }`);
          }
        }
      },
    });
  } catch (error) {
    console.error('CSS parsing error:', error);
  }
  
  return relevantRules.join('\n\n');
}

/**
 * Check if a CSS selector is relevant to a section
 */
function isRelevantSelector(
  selector: string,
  sectionSelector: string,
  classList: string[]
): boolean {
  const normalizedSelector = selector.toLowerCase();
  
  // Check direct section selector match
  if (normalizedSelector.includes(sectionSelector.toLowerCase())) {
    return true;
  }
  
  // Check class matches
  for (const className of classList) {
    if (normalizedSelector.includes(`.${className.toLowerCase()}`)) {
      return true;
    }
  }
  
  return false;
}

/**
 * Scope CSS rules to a specific section
 */
export function scopeSectionCSS(css: string, scopeSelector: string): string {
  try {
    const ast = csstree.parse(css);
    
    csstree.walk(ast, {
      enter(node: CssNode) {
        if (node.type === 'Rule' && node.prelude.type === 'SelectorList') {
          // Prepend scope selector to each selector
          csstree.walk(node.prelude, {
            enter(selectorNode: CssNode) {
              if (selectorNode.type === 'Selector' && selectorNode.children) {
                // Add scope class at the beginning
                const scopeClassNode: csstree.ClassSelector = {
                  type: 'ClassSelector',
                  name: scopeSelector.replace('.', ''),
                };
                
                const combinator: csstree.Combinator = {
                  type: 'Combinator',
                  name: ' ',
                };
                
                selectorNode.children.prependData(combinator);
                selectorNode.children.prependData(scopeClassNode);
              }
            },
          });
        }
      },
    });
    
    return csstree.generate(ast);
  } catch (error) {
    console.error('CSS scoping error:', error);
    return css;
  }
}

/**
 * Convert CSS custom properties to Liquid variables
 */
export function convertCSSVariables(css: string): string {
  let result = css;
  
  // Map common CSS variables to Shopify theme settings
  const variableMap: Record<string, string> = {
    '--color-primary': "{{ settings.color_primary }}",
    '--color-secondary': "{{ settings.color_secondary }}",
    '--color-background': "{{ settings.color_background }}",
    '--color-text': "{{ settings.color_text }}",
    '--font-body': "{{ settings.font_body.family }}",
    '--font-heading': "{{ settings.font_heading.family }}",
  };
  
  for (const [variable, liquid] of Object.entries(variableMap)) {
    const regex = new RegExp(`var\\(${variable}\\)`, 'gi');
    result = result.replace(regex, liquid);
  }
  
  return result;
}

/**
 * Inline critical CSS for a section
 */
export function inlineCriticalCSS(html: string, css: string): string {
  // Add scoped style tag at the beginning
  return `<style scoped>
${css}
</style>
${html}`;
}

/**
 * Generate CSS asset file content
 */
export function generateCSSAsset(sections: { name: string; css: string }[]): string {
  const header = `/* 
 * Theme CSS
 * Generated by ThemeForge
 */

`;
  
  const sectionStyles = sections
    .map(section => `/* Section: ${section.name} */\n${section.css}`)
    .join('\n\n');
  
  return header + sectionStyles;
}

/**
 * Minify CSS for production
 */
export function minifyCSS(css: string): string {
  try {
    const ast = csstree.parse(css);
    return csstree.generate(ast);
  } catch {
    // Fallback to basic minification
    return css
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/\s+/g, ' ')
      .replace(/\s*([{}:;,])\s*/g, '$1')
      .trim();
  }
}
