/**
 * Process JavaScript for Shopify theme compatibility
 */

export interface ProcessedJS {
  content: string;
  dependencies: string[];
  warnings: string[];
}

/**
 * Process JavaScript content for Shopify compatibility
 */
export function processJavaScript(js: string): ProcessedJS {
  const warnings: string[] = [];
  const dependencies: string[] = [];
  let content = js;

  // Remove or flag framework-specific code
  content = removeFrameworkCode(content, warnings);

  // Convert jQuery to vanilla JS if present
  if (hasJQuery(content)) {
    warnings.push('jQuery detected. Consider converting to vanilla JavaScript.');
    dependencies.push('jquery');
  }

  // Wrap in IIFE if not already
  content = wrapInIIFE(content);

  // Add Shopify-specific initialization
  content = addShopifyInit(content);

  return {
    content,
    dependencies,
    warnings,
  };
}

/**
 * Check if JavaScript uses jQuery
 */
function hasJQuery(js: string): boolean {
  return /\$\(|jQuery\(/.test(js);
}

/**
 * Remove or flag framework-specific code
 */
function removeFrameworkCode(js: string, warnings: string[]): string {
  let result = js;

  // Check for React
  if (/React\.|ReactDOM\./.test(js)) {
    warnings.push('React code detected. This will need to be converted to vanilla JS.');
    // Don't remove, just warn
  }

  // Check for Vue
  if (/new Vue\(|Vue\./.test(js)) {
    warnings.push('Vue.js code detected. This will need to be converted to vanilla JS.');
  }

  // Check for Angular
  if (/angular\.|ng-/.test(js)) {
    warnings.push('Angular code detected. This will need to be converted to vanilla JS.');
  }

  // Remove sourcemap references
  result = result.replace(/\/\/# sourceMappingURL=.+$/gm, '');

  return result;
}

/**
 * Wrap JavaScript in an IIFE if not already wrapped
 */
function wrapInIIFE(js: string): string {
  // Check if already wrapped
  if (/^\s*\(function\s*\(/.test(js) || /^\s*\(\(\)\s*=>/.test(js)) {
    return js;
  }

  return `(function() {
  'use strict';
  
${js}
})();`;
}

/**
 * Add Shopify-specific initialization code
 */
function addShopifyInit(js: string): string {
  const shopifyInit = `
// Shopify Theme Initialization
document.addEventListener('DOMContentLoaded', function() {
  // Initialize theme components
  if (typeof ThemeForge !== 'undefined') {
    ThemeForge.init();
  }
});

// Shopify Section Events
document.addEventListener('shopify:section:load', function(event) {
  // Re-initialize section after editor reload
  var section = event.target;
  if (section && typeof ThemeForge !== 'undefined') {
    ThemeForge.initSection(section);
  }
});

document.addEventListener('shopify:section:unload', function(event) {
  // Cleanup section before unload
  var section = event.target;
  if (section && typeof ThemeForge !== 'undefined') {
    ThemeForge.destroySection(section);
  }
});
`;

  return shopifyInit + '\n\n' + js;
}

/**
 * Generate the main theme JavaScript file
 */
export function generateThemeJS(): string {
  return `/* 
 * Theme JavaScript
 * Generated by ThemeForge
 */

(function() {
  'use strict';

  // Theme namespace
  window.ThemeForge = window.ThemeForge || {};

  // Initialize theme
  ThemeForge.init = function() {
    this.initMobileMenu();
    this.initSmoothScroll();
    this.initLazyLoading();
    this.initAnimations();
  };

  // Initialize a specific section
  ThemeForge.initSection = function(section) {
    // Re-initialize components within the section
    this.initLazyLoading(section);
    this.initAnimations(section);
  };

  // Destroy a section (cleanup)
  ThemeForge.destroySection = function(section) {
    // Cleanup event listeners, etc.
  };

  // Mobile menu functionality
  ThemeForge.initMobileMenu = function() {
    var menuToggle = document.querySelector('[data-menu-toggle]');
    var mobileMenu = document.querySelector('[data-mobile-menu]');

    if (menuToggle && mobileMenu) {
      menuToggle.addEventListener('click', function() {
        mobileMenu.classList.toggle('is-open');
        menuToggle.setAttribute('aria-expanded', 
          mobileMenu.classList.contains('is-open'));
      });
    }
  };

  // Smooth scroll for anchor links
  ThemeForge.initSmoothScroll = function() {
    document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
      anchor.addEventListener('click', function(e) {
        var href = this.getAttribute('href');
        if (href === '#') return;
        
        var target = document.querySelector(href);
        if (target) {
          e.preventDefault();
          target.scrollIntoView({ behavior: 'smooth' });
        }
      });
    });
  };

  // Lazy loading for images
  ThemeForge.initLazyLoading = function(container) {
    container = container || document;
    
    if ('IntersectionObserver' in window) {
      var imageObserver = new IntersectionObserver(function(entries, observer) {
        entries.forEach(function(entry) {
          if (entry.isIntersecting) {
            var image = entry.target;
            if (image.dataset.src) {
              image.src = image.dataset.src;
              image.classList.remove('lazy');
            }
            observer.unobserve(image);
          }
        });
      });

      container.querySelectorAll('img.lazy').forEach(function(image) {
        imageObserver.observe(image);
      });
    }
  };

  // Scroll animations
  ThemeForge.initAnimations = function(container) {
    container = container || document;
    
    if ('IntersectionObserver' in window) {
      var animObserver = new IntersectionObserver(function(entries) {
        entries.forEach(function(entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
          }
        });
      }, { threshold: 0.1 });

      container.querySelectorAll('[data-animate]').forEach(function(element) {
        animObserver.observe(element);
      });
    }
  };

  // Initialize on DOM ready
  document.addEventListener('DOMContentLoaded', function() {
    ThemeForge.init();
  });

})();`;
}

/**
 * Extract inline scripts from HTML
 */
export function extractInlineScripts(html: string): string[] {
  const scripts: string[] = [];
  const scriptRegex = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi;
  let match;

  while ((match = scriptRegex.exec(html)) !== null) {
    if (match[1].trim()) {
      scripts.push(match[1]);
    }
  }

  return scripts;
}

/**
 * Remove inline scripts from HTML
 */
export function removeInlineScripts(html: string): string {
  return html.replace(/<script(?![^>]*\ssrc=)[^>]*>[\s\S]*?<\/script>/gi, '');
}
